package com.example.suiri;
import org.json.*;
import java.time.*;
public class ChatTest {
 static int n;static void check(boolean ok,String message){n++;if(!ok)throw new AssertionError(message);}
 static JSONArray actions(String s)throws Exception{return new JSONArray(s);}
 public static void main(String[] args)throws Exception{LocalDateTime now=LocalDateTime.of(2026,9,17,10,0);JSONArray empty=new JSONArray();TaskActions.Result add=TaskActions.apply(empty,actions("[{\"operation\":\"create\",\"fields\":{\"title\":\"读书\",\"due\":\"2026-09-18\",\"plannedTime\":\"20:00\"}}]"),now);check(add.tasks.length()==1&&empty.length()==0,"create copies source without mutating");JSONObject t=add.tasks.getJSONObject(0);String id=t.getString("id");check(!t.optBoolean("reminder"),"no unsolicited alarm");
  TaskActions.Result moved=TaskActions.apply(add.tasks,new JSONArray().put(new JSONObject().put("operation","update").put("id",id).put("fields",new JSONObject().put("plannedTime","21:00"))),now);check(moved.tasks.getJSONObject(0).getString("plannedTime").equals("21:00"),"natural action changes time");check(moved.tasks.getJSONObject(0).getString("title").equals("读书"),"patch preserves other fields");
  TaskActions.Result done=TaskActions.apply(moved.tasks,new JSONArray().put(new JSONObject().put("operation","complete").put("id",id)),now);check(done.tasks.getJSONObject(0).optBoolean("done")&&done.tasks.getJSONObject(0).optLong("completedAt")>0,"completion timestamp");long stamp=done.tasks.getJSONObject(0).getLong("completedAt");check(TaskActions.apply(done.tasks,new JSONArray().put(new JSONObject().put("operation","complete").put("id",id)),now.plusDays(1)).tasks.getJSONObject(0).getLong("completedAt")==stamp,"idempotent completion");
  check(TaskActions.apply(done.tasks,new JSONArray().put(new JSONObject().put("operation","delete").put("id",id)),now).tasks.length()==0,"delete personal task");
  for(String fields:new String[]{"{\"due\":\"2026-99-01\"}","{\"plannedTime\":\"25:00\"}","{\"minutes\":0}","{\"source\":\"evil\"}","{\"reminder\":true,\"reminderDate\":\"2026-09-16\",\"reminderTime\":\"08:00\"}"}){boolean rejected=false;try{TaskActions.apply(add.tasks,new JSONArray().put(new JSONObject().put("operation","update").put("id",id).put("fields",new JSONObject(fields))),now);}catch(Exception e){rejected=true;}check(rejected,"invalid field rejected "+fields);}
  boolean rejected=false;try{TaskActions.apply(add.tasks,actions("[{\"operation\":\"delete\",\"id\":\"not-real\"}]"),now);}catch(Exception e){rejected=true;}check(rejected,"unknown target rejected");
  JSONArray batch=new JSONArray().put(new JSONObject().put("operation","delete").put("id",id)).put(new JSONObject().put("operation","update").put("id","bad").put("fields",new JSONObject()));try{TaskActions.apply(add.tasks,batch,now);}catch(Exception expected){}check(add.tasks.length()==1,"failed batch leaves original unchanged");
  JSONObject canvas=new JSONObject(t.toString()).put("source","canvas").put("termId","1").put("periodKey","fall");TaskActions.Result removed=TaskActions.apply(new JSONArray().put(canvas),new JSONArray().put(new JSONObject().put("operation","delete").put("id",id)),now);check(removed.tasks.getJSONObject(0).optBoolean("deleted"),"Canvas deletion tombstone");JSONArray merged=CanvasMerge.current(removed.tasks,new JSONArray().put(canvas),"1","fall");check(TaskStore.sorted(merged).isEmpty(),"Canvas sync cannot resurrect deleted task");check(!Agenda.focus(merged.getJSONObject(0),now.toLocalDate()),"removed assignment cannot notify");
  TaskActions.Result cvMoved=TaskActions.apply(new JSONArray().put(canvas),new JSONArray().put(new JSONObject().put("operation","update").put("id",id).put("fields",new JSONObject().put("due","2026-09-20"))),now);check(cvMoved.tasks.getJSONObject(0).optBoolean("dateCustomized"),"Canvas personal plan protected");
  String longText="个人习惯记录以及我希望保存的课程安排。".repeat(100);String compressed=StoredText.pack(longText);check(compressed.length()<longText.length(),"long text compressed");check(StoredText.unpack(compressed).equals(longText),"compression lossless");check(StoredText.unpack(StoredText.pack("短消息")).equals("短消息"),"small message roundtrip");String collision=StoredText.PREFIX+"not-a-real-archive";check(StoredText.unpack(StoredText.pack(collision)).equals(collision),"prefix collision escaped");
  JSONArray memories=new JSONArray();for(int i=0;i<80;i++)memories.put(new JSONObject().put("topic","主题"+i).put("value","普通记录"+i).put("updated","2026-09-17"));memories.put(new JSONObject().put("topic","睡眠").put("value","倾向十一点睡觉").put("level","多次提及"));String recall=MemoryRecall.compact(memories,"我的睡眠安排",100);check(recall.length()<=100,"memory token proxy budget enforced");check(recall.contains("睡眠"),"related habit ranked first");
  String action="{\"task_actions\":[{\"operation\":\"complete\",\"id\":\"a\"}]}";check(ChatStream.publicText("正在处理\n"+action).equals("正在处理"),"stream hides task protocol");check(LearnedMemory.visible("好的\n"+action+"\n已完成：作业").contains("已完成：作业")&&!LearnedMemory.visible(action).contains("task_actions"),"execution receipt retained while JSON hidden");
  check(TaskProposal.parse("{\"task\":{\"title\":\"阅读\",\"due\":\"2026-09-18\"}}\n{\"memory_updates\":[]}").optString("title").equals("阅读"),"multiple JSON objects do not break draft parser");
  String update="{\"memory_updates\":[{\"topic\":\"新主题\",\"value\":\"喜欢晚间读书\",\"evidence\":\"我喜欢晚间读书\"}]}";check(LearnedMemory.learn(memories,update,"我喜欢晚间读书",now.toLocalDate()).length()==82,"long-lived memories not silently capped at 30");
  check(ThinkingMode.valid("unknown").equals("none"),"unknown reasoning mode safely defaults");check(ThinkingMode.tokens("none")<ThinkingMode.tokens("low")&&ThinkingMode.tokens("low")<ThinkingMode.tokens("high")&&ThinkingMode.tokens("high")<ThinkingMode.tokens("max"),"reasoning budgets grow by depth");check(ThinkingMode.label("max").equals("最高强度"),"mode labels");
  JSONArray mixed=new JSONArray().put(new JSONObject().put("session","old").put("role","user").put("state","saved").put("content","旧会话秘密")).put(new JSONObject().put("session","new").put("role","user").put("state","saved").put("content","今天计划"));JSONArray isolated=ChatHistory.forRequest(mixed,"new");check(isolated.length()==1&&!isolated.toString().contains("旧会话秘密"),"new session excludes other conversation history");check(ChatHistory.forRequest(mixed,"empty-new").length()==0,"brand new session carries no chat history");mixed.put(new JSONObject().put("session","new").put("role","assistant").put("state","error").put("content","失败响应"));check(ChatHistory.forRequest(mixed,"new").length()==1,"failed messages never replayed as valid history");
  check(MemoryRecall.compact(memories,"学习习惯",500).length()<=500,"short cross-session habit prompt budget");
  System.out.println("PASS: "+n+" chat, memory budget, compression and automatic task action checks");
 }
}
