package com.example.suiri;
import java.time.*;
import java.util.*;
import org.json.*;
public class UpgradeTest {
 static int n;static void check(boolean ok,String message){n++;if(!ok)throw new AssertionError(message);}
 static JSONObject assignment(String id,String due)throws Exception{return new JSONObject().put("id",id).put("source","canvas").put("title","作业").put("canvasDue",due+"T10:00:00Z").put("due",due).put("termId","3").put("periodKey","2026-09-14/2027-01-15");}
 public static void main(String[] args)throws Exception{
  LocalDate now=LocalDate.of(2026,9,16);JSONObject week=assignment("a","2026-09-23"),future=assignment("b","2026-09-24"),overdue=assignment("c","2026-09-15");
  check(Agenda.focus(week,now),"7 day boundary included");check(!Agenda.focus(future,now),"8 days not urgent");check(Agenda.focus(overdue,now),"overdue stays urgent");
  week.put("due","2026-11-01");check(Agenda.focus(week,now),"urgency uses real Canvas deadline not personal date");week.put("submitted",true);check(!Agenda.focus(week,now),"submitted excluded");week.put("submitted",false).put("done",true);check(!Agenda.focus(week,now),"completed excluded");week.put("done",false).put("archived",true);check(!Agenda.focus(week,now),"archive excluded");week.put("archived",false).put("sourceMissing",true);check(!Agenda.focus(week,now),"missing source not escalated");week.put("sourceMissing",false);
  JSONObject personal=new JSONObject().put("id","p").put("due","2026-09-16").put("title","散步");List<JSONObject> order=Agenda.ordered(new JSONArray().put(future).put(personal).put(week),now);check(order.get(0)==week&&order.get(1)==personal&&order.get(2)==future,"focus then personal then ordinary Canvas");
  String mark=Agenda.monthMark(new JSONArray().put(personal).put(overdue),Collections.emptyList(),now,now);check(mark.contains("事1"),"personal month mark");check(Agenda.monthMark(new JSONArray().put(week),Collections.emptyList(),now.plusDays(7),now).contains("!1"),"Canvas deadline gets urgent month mark");
  JSONObject t1=new JSONObject("{\"id\":3,\"name\":\"2026-2027学年第一学期\",\"start_at\":\"2026-09-14T00:00:00+08:00\",\"end_at\":\"2027-01-16T00:00:00+08:00\"}");JSONArray courses=new JSONArray().put(new JSONObject().put("id",1).put("term",t1)).put(new JSONObject().put("id",2).put("term",t1)).put(new JSONObject().put("id",3).put("enrollment_term_id",4));JSONArray terms=CanvasTerms.options(courses);check(terms.length()==2,"term dedup");check(CanvasTerms.filter(courses,"3").length()==2,"only selected term courses");check(CanvasTerms.current(terms,now.atStartOfDay(Schedule.ZONE).toInstant()).equals("3"),"term date selection");terms.put(new JSONObject(t1.toString()).put("id",5));check(CanvasTerms.current(terms,now.atStartOfDay(Schedule.ZONE).toInstant()).isEmpty(),"ambiguous dates not guessed");
  SchoolCalendar.Period fall=SchoolCalendar.current(now);check(fall.start.equals(LocalDate.of(2026,9,14))&&fall.end.equals(LocalDate.of(2027,1,15)),"official fall boundaries");check(SchoolCalendar.current(LocalDate.of(2026,9,13)).gap,"summer gap ends before fall");check(SchoolCalendar.current(LocalDate.of(2027,1,16)).gap,"winter gap starts day after final day");check(SchoolCalendar.current(LocalDate.of(2027,2,21)).gap,"winter gap includes final day");check(SchoolCalendar.current(LocalDate.of(2027,2,22))==null,"unknown spring end not invented");check(SchoolCalendar.matching(CanvasTerms.options(courses),fall).equals("3"),"official period name maps Canvas term");check(SchoolCalendar.matching(CanvasTerms.options(courses),SchoolCalendar.current(LocalDate.of(2026,8,1))).isEmpty(),"gap not mapped to unrelated term");
  JSONObject old=assignment("a","2026-09-20").put("notes","保留备注").put("done",true).put("minutes",80),prior=assignment("old","2026-06-03").put("termId","2").put("notes","旧备注").put("reminder",true);JSONArray merged=CanvasMerge.current(new JSONArray().put(old).put(prior).put(personal),new JSONArray().put(week),"3",fall.key);check(merged.length()==3,"archive retains data");check(merged.getJSONObject(0).optString("notes").equals("保留备注")&&merged.getJSONObject(0).optBoolean("done"),"sync preserves notes and done");check(merged.getJSONObject(1).optBoolean("archived")&&!merged.getJSONObject(1).optBoolean("reminder"),"old term archived and reminder disabled");check(!merged.getJSONObject(2).optBoolean("archived"),"personal tasks preserved");
  JSONObject note=NoteProposal.parse("建议\n```json\n{\"note_change\":{\"id\":\"p\",\"operation\":\"append\",\"text\":\"带水\"}}\n```");check(NoteProposal.next("跑步",note).equals("跑步\n带水"),"append note");note.put("operation","clear");check(NoteProposal.next("原文",note).isEmpty(),"clear note");note.put("operation","replace");check(NoteProposal.next("原文",note).equals("带水"),"replace note");boolean rejected=false;try{NoteProposal.parse("{\"note_change\":{\"id\":\"p\",\"operation\":\"delete_task\",\"text\":\"x\"}}");}catch(Exception e){rejected=true;}check(rejected,"invalid AI action rejected");
  String observation="{\"memory_updates\":[{\"topic\":\"学习时段\",\"value\":\"偏好晚间学习\",\"evidence\":\"我喜欢晚上学习\"}]}";JSONArray memory=LearnedMemory.learn(new JSONArray(),observation,"我喜欢晚上学习",now);check(memory.length()==1&&memory.getJSONObject(0).optString("level").equals("待观察"),"first observation tentative");check(LearnedMemory.learn(new JSONArray(),observation,"今天下雨了",now).length()==0,"unfounded evidence rejected");JSONArray duplicate=LearnedMemory.learn(memory,observation,"我喜欢晚上学习",now);check(duplicate.getJSONObject(0).getJSONArray("proofs").length()==1,"replayed evidence not inflated");String second=observation.replace("我喜欢晚上学习","我晚上学习更专注");memory=LearnedMemory.learn(memory,second,"我晚上学习更专注",now.plusDays(1));check(memory.getJSONObject(0).optString("level").equals("多次提及"),"distinct corroborating evidence raises level");memory.getJSONObject(0).put("locked",true).put("value","用户纠正");memory=LearnedMemory.learn(memory,observation,"我喜欢晚上学习",now);check(memory.getJSONObject(0).optString("value").equals("用户纠正"),"user correction never overwritten");
  check(LearnedMemory.visible("好的\n```json\n"+observation+"\n```").equals("好的"),"internal memory JSON hidden from conversational UI");check(LearnedMemory.visible("回答 {普通文字} 结束").contains("{普通文字}"),"normal text preserved");
  long time=now.atTime(20,0).atZone(Schedule.ZONE).toInstant().toEpochMilli();JSONArray finished=new JSONArray().put(personal.put("done",true).put("completedAt",time)).put(new JSONObject().put("done",true));check(LearnedMemory.behavior(finished,Instant.ofEpochMilli(time+1000)).contains("1 次"),"legacy done without timestamp not invented");
  System.out.println("PASS: "+n+" upgrade checks (priority, school calendar, term filtering, note safety, learned memory)");
 }
}
