package com.example.suiri;
import android.content.*;
import android.graphics.*;
import android.graphics.pdf.PdfDocument;
import android.text.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.zip.*;
public final class ChatFiles {
 public static void image(String text,OutputStream out)throws IOException{TextPaint paint=new TextPaint(Paint.ANTI_ALIAS_FLAG);paint.setColor(0xff263238);paint.setTextSize(30);StaticLayout layout=StaticLayout.Builder.obtain(text,0,text.length(),paint,980).setLineSpacing(10,1).setIncludePad(false).build();if(layout.getHeight()>18000)throw new IOException("回答过长，请保存为 PDF 或文本");Bitmap b=Bitmap.createBitmap(1080,layout.getHeight()+140,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(Color.WHITE);c.translate(50,70);layout.draw(c);b.compress(Bitmap.CompressFormat.PNG,100,out);b.recycle();}
 public static void pdf(String text,OutputStream out)throws IOException{TextPaint paint=new TextPaint(Paint.ANTI_ALIAS_FLAG);paint.setTextSize(15);paint.setColor(Color.BLACK);StaticLayout layout=StaticLayout.Builder.obtain(text,0,text.length(),paint,515).setLineSpacing(4,1).build();PdfDocument doc=new PdfDocument();try{int first=0,pageNo=1;while(first<layout.getLineCount()){int top=layout.getLineTop(first),last=first;while(last+1<layout.getLineCount()&&layout.getLineBottom(last+1)-top<740)last++;int bottom=layout.getLineBottom(last);PdfDocument.Page page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,pageNo++).create());Canvas canvas=page.getCanvas();canvas.translate(40,45);canvas.clipRect(0,0,515,bottom-top);canvas.translate(0,-top);layout.draw(canvas);doc.finishPage(page);first=last+1;}doc.writeTo(out);}finally{doc.close();}}
 public static void backup(Context c,ChatStore db,OutputStream out)throws Exception{try(ZipOutputStream zip=new ZipOutputStream(out)){zip.putNextEntry(new ZipEntry("chat.json"));zip.write(db.backup(c).toString().getBytes(StandardCharsets.UTF_8));zip.closeEntry();File[] files=Attachments.folder(c).listFiles();if(files!=null)for(File f:files){if(!f.isFile())continue;zip.putNextEntry(new ZipEntry("files/"+f.getName()));try(InputStream in=new FileInputStream(f)){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)zip.write(b,0,n);}zip.closeEntry();}}}
 public static void restore(Context c,ChatStore db,InputStream in)throws Exception{JSONObject metadata=null;long total=0;java.util.Map<String,byte[]> staged=new java.util.HashMap<>();try(ZipInputStream zip=new ZipInputStream(in)){ZipEntry entry;while((entry=zip.getNextEntry())!=null){if(entry.isDirectory())continue;String name=entry.getName();byte[] bytes=Attachments.read(zip,name.equals("chat.json")?30_000_000:10*1024*1024);total+=bytes.length;if(total>80_000_000)throw new IOException("备份超过本版 80MB 导入上限");if(name.equals("chat.json"))metadata=new JSONObject(new String(bytes,StandardCharsets.UTF_8));else if(name.startsWith("files/")){String base=name.substring(6);Attachments.local(c,base);staged.put(base,bytes);}else throw new IOException("备份含未知文件");}}
  if(metadata==null||!metadata.optString("format").equals("suiri-chat-1"))throw new IOException("无效聊天备份");for(java.util.Map.Entry<String,byte[]> entry:staged.entrySet()){File file=Attachments.local(c,entry.getKey());if(file.exists()){try(InputStream old=new FileInputStream(file)){if(!java.util.Arrays.equals(Attachments.read(old,10*1024*1024),entry.getValue()))throw new IOException("附件同名但内容不同，已停止导入");}}}for(java.util.Map.Entry<String,byte[]> entry:staged.entrySet()){File file=Attachments.local(c,entry.getKey());if(!file.exists())try(OutputStream out=new FileOutputStream(file)){out.write(entry.getValue());}}db.restore(c,metadata);
 }
}
