package com.example.suiri;
import android.content.*;
import android.database.*;
import android.database.sqlite.*;
import org.json.*;
import java.util.*;
public class ChatStore extends SQLiteOpenHelper {
 public ChatStore(Context c){super(c,"assistant.db",null,1);migrate(c);}
 public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE sessions(id TEXT PRIMARY KEY,title TEXT,topic TEXT,created INTEGER,updated INTEGER)");db.execSQL("CREATE TABLE messages(id INTEGER PRIMARY KEY AUTOINCREMENT,session TEXT,role TEXT,content TEXT,time INTEGER,model TEXT,state TEXT,attachments TEXT,search TEXT)");db.execSQL("CREATE INDEX history ON messages(session,id)");db.execSQL("CREATE TABLE memory_log(id INTEGER PRIMARY KEY AUTOINCREMENT,time INTEGER,body TEXT)");}
 public void onUpgrade(SQLiteDatabase db,int a,int b){}
 synchronized void migrate(Context c){if(TaskStore.prefs(c).getBoolean("chatMigrated04",false))return;SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{if(sessions("").length()==0){JSONArray old=new JSONArray(TaskStore.prefs(c).getString("chat","[]"));if(old.length()>0){String id=create("旧版聊天记录","旧版迁移");for(int i=0;i<old.length();i++){JSONObject m=old.getJSONObject(i);append(id,m.optString("role"),m.optString("content"),"旧模型","saved",new JSONArray(),0);}}}db.setTransactionSuccessful();}catch(Exception e){throw new IllegalStateException("旧聊天迁移失败，原数据保留",e);}finally{db.endTransaction();}TaskStore.prefs(c).edit().putBoolean("chatMigrated04",true).commit();}
 public synchronized String create(String title,String topic){String id=UUID.randomUUID().toString();ContentValues v=new ContentValues();v.put("id",id);v.put("title",title);v.put("topic",topic);v.put("created",System.currentTimeMillis());v.put("updated",System.currentTimeMillis());getWritableDatabase().insertOrThrow("sessions",null,v);return id;}
 public synchronized long append(String session,String role,String content,String model,String state,JSONArray files,long time){ContentValues v=new ContentValues();v.put("session",session);v.put("role",role);v.put("content",StoredText.pack(content));v.put("search",content.substring(0,Math.min(512,content.length())));v.put("time",time);v.put("model",model);v.put("state",state);v.put("attachments",StoredText.pack(files.toString()));long id=getWritableDatabase().insertOrThrow("messages",null,v);ContentValues update=new ContentValues();update.put("updated",System.currentTimeMillis());getWritableDatabase().update("sessions",update,"id=?",new String[]{session});return id;}
 public void state(long id,String state){ContentValues v=new ContentValues();v.put("state",state);getWritableDatabase().update("messages",v,"id=?",new String[]{Long.toString(id)});}
 public void rename(String id,String title,String topic){ContentValues v=new ContentValues();v.put("title",title);v.put("topic",topic);getWritableDatabase().update("sessions",v,"id=?",new String[]{id});}
 public JSONArray sessions(String search){return query("SELECT * FROM sessions WHERE title LIKE ? OR topic LIKE ? OR id IN (SELECT session FROM messages WHERE search LIKE ?) ORDER BY updated DESC",new String[]{"%"+search+"%","%"+search+"%","%"+search+"%"});}
 public JSONArray messages(String session,int limit){JSONArray rows=query("SELECT * FROM (SELECT * FROM messages WHERE session=? ORDER BY id DESC LIMIT ?) ORDER BY id",new String[]{session,Integer.toString(limit)});for(int i=0;i<rows.length();i++)try{JSONObject m=rows.getJSONObject(i);m.put("content",StoredText.unpack(m.optString("content")));m.put("attachments",StoredText.unpack(m.optString("attachments","[]")));}catch(JSONException e){throw new IllegalStateException(e);}return rows;}
 public JSONArray query(String sql,String[] args){JSONArray list=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery(sql,args)){while(c.moveToNext()){JSONObject row=new JSONObject();for(int i=0;i<c.getColumnCount();i++){if(c.getType(i)==Cursor.FIELD_TYPE_INTEGER)row.put(c.getColumnName(i),c.getLong(i));else row.put(c.getColumnName(i),c.getString(i));}list.put(row);}}catch(JSONException e){throw new IllegalStateException(e);}return list;}
 public void snapshot(String json){JSONArray last=query("SELECT body FROM memory_log ORDER BY id DESC LIMIT 1",new String[]{});if(last.length()>0&&StoredText.unpack(last.optJSONObject(0).optString("body")).equals(json))return;ContentValues v=new ContentValues();v.put("time",System.currentTimeMillis());v.put("body",StoredText.pack(json));getWritableDatabase().insertOrThrow("memory_log",null,v);}
 public JSONObject backup(Context c)throws JSONException{return new JSONObject().put("format","suiri-chat-1").put("sessions",query("SELECT * FROM sessions",new String[]{})).put("messages",query("SELECT * FROM messages ORDER BY id",new String[]{})).put("memory_log",query("SELECT * FROM memory_log ORDER BY id",new String[]{})).put("learnedMemory",TaskStore.prefs(c).getString("learnedMemory","[]")).put("memory",TaskStore.prefs(c).getString("memory",""));}
 public synchronized void restore(Context c,JSONObject backup)throws JSONException{if(!backup.optString("format").equals("suiri-chat-1"))throw new JSONException("不是saber喵聊天备份");JSONArray sessions=backup.getJSONArray("sessions"),messages=backup.getJSONArray("messages");SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{Map<String,String> mapping=new HashMap<>();for(int i=0;i<sessions.length();i++){JSONObject old=sessions.getJSONObject(i);mapping.put(old.getString("id"),create(old.optString("title"),old.optString("topic")));}for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);String id=mapping.get(m.getString("session"));if(id==null)throw new JSONException("备份会话不完整");append(id,m.getString("role"),StoredText.unpack(m.getString("content")),m.optString("model"),"saved",new JSONArray(StoredText.unpack(m.optString("attachments","[]"))),m.optLong("time"));}db.setTransactionSuccessful();}finally{db.endTransaction();}
  JSONArray merged=new JSONArray(TaskStore.prefs(c).getString("learnedMemory","[]")),incoming=new JSONArray(backup.optString("learnedMemory","[]"));for(int i=0;i<incoming.length();i++){JSONObject m=incoming.getJSONObject(i);boolean exists=false;for(int j=0;j<merged.length();j++)if(merged.getJSONObject(j).optString("topic").equals(m.optString("topic")))exists=true;if(!exists)merged.put(m);}TaskStore.prefs(c).edit().putString("learnedMemory",merged.toString()).putLong("memoryEpoch",TaskStore.prefs(c).getLong("memoryEpoch",0)+1).commit();if(TaskStore.prefs(c).getString("memory","").isEmpty())TaskStore.prefs(c).edit().putString("memory",backup.optString("memory","")).commit();snapshot(merged.toString());
 }
}
