package com.example.suiri;
import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;

/** Translucent activity: underlying agenda keeps its scroll position; one current utterance only. */
public class PetChatActivity extends ChatActivity {
 boolean weatherIntro;ImageView portrait;
 @Override public void onCreate(Bundle state){weatherIntro=getIntent().getBooleanExtra("weather",false);super.onCreate(state);if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,()->closePet());getWindow().setDimAmount(.25f);getWindow().addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);}
 @Override void render(){if(db==null)return;if(chatInput!=null)draft=chatInput.getText().toString();root=column();root.setBackgroundColor(android.graphics.Color.TRANSPARENT);setContentView(root);View dismiss=new View(this);root.addView(dismiss,new LinearLayout.LayoutParams(-1,0,1));dismiss.setOnClickListener(v->closePet());LinearLayout sheet=column();sheet.setPadding(dp(16),dp(12),dp(16),dp(10));sheet.setBackground(Saber.shape(this,Saber.SURFACE,28,Saber.LINE));root.addView(sheet,new LinearLayout.LayoutParams(-1,dp(535)));
 LinearLayout heading=new LinearLayout(this);TextView title=text("Saber",27);title.setTypeface(android.graphics.Typeface.SERIF,android.graphics.Typeface.BOLD);title.setTextColor(Saber.GOLD);heading.addView(title,new LinearLayout.LayoutParams(0,-2,1));heading.addView(button("关闭",()->closePet()));sheet.addView(heading);TextView subtitle=text("骑士助手 · "+(busy?"正在回应":"与你并肩"),12);subtitle.setTextColor(Saber.GOLD);if(busy)sheet.addView(subtitle);
 String utterance=Weather.advice(this),raw="";JSONArray history=db.messages(session,20);if(!weatherIntro)for(int i=history.length()-1;i>=0;i--){JSONObject m=history.optJSONObject(i);if(m.optString("role").equals("assistant")||m.optString("role").equals("error")){raw=m.optString("content");utterance=Saber.clean(raw);break;}}if(busy)utterance=stream.isEmpty()?"亲爱的master，请稍候，我正在整理。":Saber.streaming(stream);
 LinearLayout stage=new LinearLayout(this);stage.setGravity(Gravity.CENTER_VERTICAL);messagesView=new ScrollView(this);LinearLayout words=column();words.setPadding(dp(12),dp(10),dp(12),dp(10));words.setBackground(Saber.shape(this,Saber.BG,20,Saber.GOLD));TextView speaker=text("S A B E R",12);speaker.setTextColor(Saber.GOLD);words.addView(speaker);live=text(utterance,17);live.setTextIsSelectable(true);words.addView(live);messagesView.addView(words);stage.addView(messagesView,new LinearLayout.LayoutParams(0,-1,1));portrait=Saber.picture(this,busy?0:weatherIntro?0:Saber.emotion(raw),false);portrait.setOnClickListener(v->Saber.previews(this));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(138),dp(180));pp.setMargins(dp(10),0,0,0);stage.addView(portrait,pp);sheet.addView(stage,new LinearLayout.LayoutParams(-1,0,1));
 TextView weather=text(Weather.summary(this),12);weather.setTextColor(Saber.MUTED);weather.setOnClickListener(v->WeatherUi.details(this));sheet.addView(weather);LinearLayout options=new LinearLayout(this);options.addView(button(ThinkingMode.label(prefs.getString("thinking","none")),()->thinkingDialog()),new LinearLayout.LayoutParams(0,dp(42),1));options.addView(button("收起",()->closePet()),new LinearLayout.LayoutParams(0,dp(42),1));sheet.addView(options);
 if(attached.length()>0)sheet.addView(button("已附 "+attached.length()+" 个文件 · 点击清空",()->{if(!busy){attached=new JSONArray();render();}}));LinearLayout compose=new LinearLayout(this);compose.setGravity(Gravity.CENTER_VERTICAL);Button plus=button("附件",()->pickAttachment());plus.setEnabled(!busy&&!importing);compose.addView(plus,new LinearLayout.LayoutParams(dp(56),dp(48)));chatInput=new EditText(this);chatInput.setTextColor(Saber.INK);chatInput.setHintTextColor(Saber.MUTED);chatInput.setTextSize(16);chatInput.setHint("与 Saber 说些什么…");chatInput.setText(draft);chatInput.setMaxLines(3);chatInput.setBackground(Saber.shape(this,Saber.BG,18,Saber.LINE));chatInput.setPadding(dp(12),dp(8),dp(12),dp(8));compose.addView(chatInput,new LinearLayout.LayoutParams(0,-2,1));Button send=button(busy?"稍候":"发送",()->send(chatInput.getText().toString(),true));send.setEnabled(!busy&&!importing);compose.addView(send,new LinearLayout.LayoutParams(dp(60),dp(48)));sheet.addView(compose);TextView hint=text(importing?"正在读取附件…":"",10);hint.setTextColor(Saber.MUTED);if(importing)sheet.addView(hint);
 root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()),ime=insets.getInsets(WindowInsets.Type.ime());boolean keyboard=insets.isVisible(WindowInsets.Type.ime());root.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,ime.bottom));int available=getResources().getDisplayMetrics().heightPixels-bars.top-Math.max(bars.bottom,ime.bottom);sheet.getLayoutParams().height=keyboard?available:Math.min(dp(600),(int)(available*.76f));portrait.setVisibility(keyboard?View.GONE:View.VISIBLE);weather.setVisibility(keyboard?View.GONE:View.VISIBLE);subtitle.setVisibility(keyboard?View.GONE:View.VISIBLE);sheet.requestLayout();return insets;});root.requestApplyInsets();}
 @Override void send(String q,boolean learn){weatherIntro=false;super.send(q,learn);}
 void closePet(){if(busy||importing){toast("请等当前回复完成后收起，避免重复执行安排");return;}finish();}
 @Override public void onBackPressed(){closePet();}
}
