package com.example.suiri;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;
/** Small editable Open XML deck; no server or desktop Office needed on the phone. */
public final class PptxExporter {
 static final String P="http://schemas.openxmlformats.org/presentationml/2006/main",A="http://schemas.openxmlformats.org/drawingml/2006/main",R="http://schemas.openxmlformats.org/officeDocument/2006/relationships";
 static final String GROUP="<p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"0\" cy=\"0\"/><a:chOff x=\"0\" y=\"0\"/><a:chExt cx=\"0\" cy=\"0\"/></a:xfrm></p:grpSpPr>";
 static class Slide{String title;List<String> lines=new ArrayList<>();Slide(String t){title=t;}}
 static String xml(String text){StringBuilder b=new StringBuilder();text.codePoints().filter(c->c==9||c==10||c==13||c>=32&&c<=0xD7FF||c>=0xE000&&c<=0xFFFD||c>=0x10000&&c<=0x10FFFF).forEach(b::appendCodePoint);return b.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 static List<String> wrap(String line){List<String> out=new ArrayList<>();StringBuilder b=new StringBuilder();int weight=0;for(int cp:line.codePoints().toArray()){int w=cp>255?2:1;if(weight+w>58){out.add(b.toString());b.setLength(0);weight=0;}b.appendCodePoint(cp);weight+=w;}if(b.length()>0)out.add(b.toString());return out;}
 static List<Slide> parse(String text)throws IOException{if(text==null||text.trim().isEmpty())throw new IOException("回答为空，无法生成PPT");if(text.length()>60000)throw new IOException("内容过长，请分成多份PPT");List<Slide> slides=new ArrayList<>();Slide current=new Slide("演示文稿");boolean code=false;for(String raw:text.replace("\r","").split("\n")){String line=raw.trim();if(line.startsWith("```")){code=!code;continue;}if(line.isEmpty())continue;if(!code&&line.matches("#{1,3}\\s+.*")){if(!current.lines.isEmpty())slides.add(current);String title=line.replaceFirst("^#{1,3}\\s+","").replace("**","");current=new Slide(title.length()>42?title.substring(0,42)+"…":title);if(title.length()>42)current.lines.addAll(wrap(title));continue;}if(!code&&line.matches("[-*_]{3,}")){if(!current.lines.isEmpty())slides.add(current);current=new Slide("继续");continue;}line=line.replace("**","").replaceFirst("^[-*]\\s+","• ");for(String part:wrap(line)){if(current.lines.size()>=10){slides.add(current);current=new Slide(current.title.replace("（续）","")+"（续）");}current.lines.add(part);}}if(!current.lines.isEmpty()||slides.isEmpty())slides.add(current);if(slides.size()>80)throw new IOException("超过80页，请缩短内容");return slides;}
 static void put(ZipOutputStream z,String name,String text)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+text).getBytes(StandardCharsets.UTF_8));z.closeEntry();}
 static String rel(String id,String kind,String target){return "<Relationship Id=\""+id+"\" Type=\""+R+"/"+kind+"\" Target=\""+target+"\"/>";}
 static String rels(String text){return "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"+text+"</Relationships>";}
 static String shape(int id,String title,List<String> lines,int x,int y,int w,int h,int size,String color){StringBuilder t=new StringBuilder("<p:sp><p:nvSpPr><p:cNvPr id=\""+id+"\" name=\""+xml(title)+"\"/><p:cNvSpPr txBox=\"1\"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x=\""+x+"\" y=\""+y+"\"/><a:ext cx=\""+w+"\" cy=\""+h+"\"/></a:xfrm><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom><a:noFill/></p:spPr><p:txBody><a:bodyPr wrap=\"square\"><a:spAutoFit/></a:bodyPr><a:lstStyle/>");for(String line:lines)t.append("<a:p><a:pPr><a:spcAft><a:spcPts val=\"500\"/></a:spcAft></a:pPr><a:r><a:rPr lang=\"zh-CN\" sz=\"").append(size).append("\"><a:solidFill><a:srgbClr val=\"").append(color).append("\"/></a:solidFill><a:latin typeface=\"Arial\"/><a:ea typeface=\"Microsoft YaHei\"/></a:rPr><a:t>").append(xml(line)).append("</a:t></a:r><a:endParaRPr lang=\"zh-CN\"/></a:p>");return t+"</p:txBody></p:sp>";}
 static String root(String tag){return "<p:"+tag+" xmlns:p=\""+P+"\" xmlns:a=\""+A+"\" xmlns:r=\""+R+"\"";}
 public static void write(String text,OutputStream out)throws IOException{List<Slide> slides=parse(text);try(ZipOutputStream z=new ZipOutputStream(out)){StringBuilder types=new StringBuilder("<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/>");String[][] parts={{"/ppt/presentation.xml","presentation"},{"/ppt/slideMasters/slideMaster1.xml","slideMaster"},{"/ppt/slideLayouts/slideLayout1.xml","slideLayout"}};for(String[] part:parts)types.append("<Override PartName=\"").append(part[0]).append("\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.").append(part[1].equals("presentation")?"presentation.main":part[1]).append("+xml\"/>");types.append("<Override PartName=\"/ppt/theme/theme1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.theme+xml\"/>");StringBuilder ids=new StringBuilder(),relationships=new StringBuilder(rel("master","slideMaster","slideMasters/slideMaster1.xml"));
  for(int i=0;i<slides.size();i++){int n=i+1;types.append("<Override PartName=\"/ppt/slides/slide").append(n).append(".xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slide+xml\"/>");ids.append("<p:sldId id=\"").append(256+i).append("\" r:id=\"slide").append(n).append("\"/>");relationships.append(rel("slide"+n,"slide","slides/slide"+n+".xml"));Slide slide=slides.get(i);put(z,"ppt/slides/slide"+n+".xml",root("sld")+"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val=\"101D35\"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree>"+GROUP+shape(2,"标题",Arrays.asList(slide.title),600000,350000,10900000,1100000,3200,"E7C681")+shape(3,"正文",slide.lines,600000,1600000,10900000,4700000,2400,"F4F0E8")+shape(4,"页码",Arrays.asList(n+" / "+slides.size()),11000000,6400000,800000,300000,1200,"B4C5E1")+"</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>");put(z,"ppt/slides/_rels/slide"+n+".xml.rels",rels(rel("layout","slideLayout","../slideLayouts/slideLayout1.xml")));}
  put(z,"[Content_Types].xml",types+"</Types>");put(z,"_rels/.rels",rels(rel("presentation","officeDocument","ppt/presentation.xml")));put(z,"ppt/presentation.xml",root("presentation")+"><p:sldMasterIdLst><p:sldMasterId id=\"2147483648\" r:id=\"master\"/></p:sldMasterIdLst><p:sldIdLst>"+ids+"</p:sldIdLst><p:sldSz cx=\"12192000\" cy=\"6858000\" type=\"screen16x9\"/><p:notesSz cx=\"6858000\" cy=\"9144000\"/></p:presentation>");put(z,"ppt/_rels/presentation.xml.rels",rels(relationships.toString()));
  put(z,"ppt/slideMasters/slideMaster1.xml",root("sldMaster")+"><p:cSld><p:spTree>"+GROUP+"</p:spTree></p:cSld><p:clrMap accent1=\"accent1\" accent2=\"accent2\" accent3=\"accent3\" accent4=\"accent4\" accent5=\"accent5\" accent6=\"accent6\" bg1=\"lt1\" bg2=\"lt2\" folHlink=\"folHlink\" hlink=\"hlink\" tx1=\"dk1\" tx2=\"dk2\"/><p:sldLayoutIdLst><p:sldLayoutId id=\"2147483649\" r:id=\"layout\"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>");put(z,"ppt/slideMasters/_rels/slideMaster1.xml.rels",rels(rel("layout","slideLayout","../slideLayouts/slideLayout1.xml")+rel("theme","theme","../theme/theme1.xml")));
  put(z,"ppt/slideLayouts/slideLayout1.xml",root("sldLayout")+" type=\"blank\" preserve=\"1\"><p:cSld name=\"Blank\"><p:spTree>"+GROUP+"</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>");put(z,"ppt/slideLayouts/_rels/slideLayout1.xml.rels",rels(rel("master","slideMaster","../slideMasters/slideMaster1.xml")));put(z,"ppt/theme/theme1.xml",theme());
 }}
 static String theme(){String[] names={"dk1","lt1","dk2","lt2","accent1","accent2","accent3","accent4","accent5","accent6","hlink","folHlink"},colors={"101D35","FFFFFF","1B2D4E","F4F0E8","E7C681","426DC0","377F7B","946580","886E43","67598A","426DC0","67598A"};StringBuilder c=new StringBuilder();for(int i=0;i<names.length;i++)c.append("<a:").append(names[i]).append("><a:srgbClr val=\"").append(colors[i]).append("\"/></a:").append(names[i]).append(">");String fill="<a:solidFill><a:schemeClr val=\"phClr\"/></a:solidFill>",line="<a:ln w=\"9525\">"+fill+"<a:prstDash val=\"solid\"/></a:ln>";return "<a:theme xmlns:a=\""+A+"\" name=\"Saber\"><a:themeElements><a:clrScheme name=\"Saber\">"+c+"</a:clrScheme><a:fontScheme name=\"Saber\"><a:majorFont><a:latin typeface=\"Arial\"/><a:ea typeface=\"Microsoft YaHei\"/><a:cs typeface=\"Arial\"/></a:majorFont><a:minorFont><a:latin typeface=\"Arial\"/><a:ea typeface=\"Microsoft YaHei\"/><a:cs typeface=\"Arial\"/></a:minorFont></a:fontScheme><a:fmtScheme name=\"Saber\"><a:fillStyleLst>"+fill+fill+fill+"</a:fillStyleLst><a:lnStyleLst>"+line+line+line+"</a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst>"+fill+fill+fill+"</a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>";}
}
