package com.example.suiri;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.view.*;
import android.widget.*;
import org.json.*;

/** Shared local artwork and bounded expression metadata. Images never enter the model prompt. */
public final class Saber {
 public static final int BG=0xff101d35,SURFACE=0xff1b2d4e,LINE=0xff3a527b,INK=0xfff4f0e8,MUTED=0xffb4c5e1,GOLD=0xffe7c681,BLUE=0xff426dc0;
 static final String[] EMOTIONS={"neutral","happy","angry","sad","surprised","speechless","shy","proud","tired"};
 static final String[] LABELS={"平静","开心","生气","难过","惊讶","无语","害羞","得意","疲惫"};
 static Bitmap sheet,head,widgetHead;static Bitmap[] faces=new Bitmap[9];
 public static int index(String value){for(int i=0;i<EMOTIONS.length;i++)if(EMOTIONS[i].equals(value))return i;return 0;}
 public static int emotion(String reply){return index(LearnedMemory.structured(reply,"emotion").optString("emotion"));}
 public static String clean(String s){return LearnedMemory.visible(s);}
 public static String streaming(String s){java.util.regex.Matcher m=java.util.regex.Pattern.compile("\\{\\s*\"(?:emotion|task_actions|memory_updates)\"\\s*:").matcher(s);int cut=m.find()?m.start():s.indexOf("```json");return clean(cut>=0?s.substring(0,cut):s);}

 public static String prompt(){return "你是生活助手 Saber，参考 Fate/stay night 中阿尔托莉雅的气质：端正、认真、自律，有骑士的责任感，关心用户但表达克制。\n按用户偏好称呼他“亲爱的master”，在开场、提醒或强调时自然使用，不必每句话重复。旧记录或记忆中的主人、御主是过期称呼，不沿用；当前称呼固定为亲爱的master。\n中文表达简洁、坚定、礼貌。先给结论，再说明必要原因；关心通过具体建议和可靠行动体现。避免客服腔、撒娇、卖萌、过度赞美和反复宣誓。\n尊重亲爱的master的选择，也保持判断。遇到过劳、时间冲突或明显不合理的安排，平静指出问题，给出可行替代方案。不要一味附和或训斥。\n日常相处可以稍显认真得可爱、偶有不动声色的幽默；谈到饭菜可自然表现兴趣，但不要强行每轮提食物或战斗。\n安排任务时准确复述关键时间与结果。只有工具确认成功后才说“已完成”；失败直接说明原因。现实功能与角色表达分开，不虚构执行结果、天气或用户习惯。\n天气先说明白天和夜间预报，再简短交代雨伞、保暖等行动；概率使用“可能”，数据缺失或过期如实说明。\n表情随本轮台词自然变化，默认平静；表达担忧不用发怒，完成任务可欣慰。保留应用现有任务操作与表情 JSON 协议。\n不冒充真人，不声称拥有手机未授予的能力。末尾JSON可额外附emotion字段，值只能为neutral/happy/angry/sad/surprised/speechless/shy/proud/tired，表示你本轮的表现，不诊断用户情绪。";}
 public static GradientDrawable shape(Context c,int color,int radius,int border){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(c.getResources().getDisplayMetrics().density*radius);if(border!=0)d.setStroke(1,border);return d;}
 public static synchronized Bitmap face(Context c,int n){n=Math.max(0,Math.min(n,8));if(faces[n]==null){if(n==8){Bitmap b=BitmapFactory.decodeResource(c.getResources(),R.drawable.saber_tired);faces[n]=Bitmap.createScaledBitmap(b,260,260,true);if(b!=faces[n])b.recycle();return faces[n];}if(sheet==null)sheet=BitmapFactory.decodeResource(c.getResources(),R.drawable.saber_moods);int x=24+(n%3)*406,y=25+(n/3)*409;Bitmap crop=Bitmap.createBitmap(sheet,x,y,390,395);faces[n]=Bitmap.createScaledBitmap(crop,260,263,true);crop.recycle();}return faces[n];}
 public static synchronized Bitmap widgetHead(Context c){if(widgetHead==null){Bitmap b=BitmapFactory.decodeResource(c.getResources(),R.drawable.saber_widget);widgetHead=Bitmap.createScaledBitmap(b,144,144,true);if(b!=widgetHead)b.recycle();}return widgetHead;}
 public static synchronized Bitmap head(Context c){if(head==null){Bitmap b=BitmapFactory.decodeResource(c.getResources(),R.drawable.saber_head);Bitmap cropped=Bitmap.createBitmap(b,280,280,720,720);head=Bitmap.createScaledBitmap(cropped,144,144,true);cropped.recycle();b.recycle();}return head;}
 public static ImageView picture(MainActivity a,int emotion,boolean avatar){ImageView v=new ImageView(a){android.animation.ObjectAnimator breathe;@Override protected void onAttachedToWindow(){super.onAttachedToWindow();if(android.animation.ValueAnimator.areAnimatorsEnabled()){breathe=android.animation.ObjectAnimator.ofFloat(this,"alpha",.94f,1f,.94f);breathe.setDuration(2600);breathe.setRepeatCount(android.animation.ValueAnimator.INFINITE);breathe.start();}}@Override protected void onDetachedFromWindow(){if(breathe!=null)breathe.cancel();super.onDetachedFromWindow();}};v.setImageBitmap(avatar?head(a):face(a,emotion));v.setScaleType(ImageView.ScaleType.FIT_CENTER);v.setBackground(shape(a,SURFACE,avatar?100:24,LINE));v.setClipToOutline(true);v.setContentDescription(avatar?"打开 Saber 对话":"Saber · "+LABELS[Math.max(0,Math.min(emotion,8))]);return v;}
 public static void previews(MainActivity a){LinearLayout list=a.column();for(int r=0;r<3;r++){LinearLayout row=new LinearLayout(a);for(int c=0;c<3;c++){final int n=r*3+c;LinearLayout cell=a.column();ImageView image=picture(a,n,false);cell.addView(image,new LinearLayout.LayoutParams(-1,a.dp(105)));TextView label=a.text(LABELS[n],13);label.setGravity(Gravity.CENTER);cell.addView(label);row.addView(cell,new LinearLayout.LayoutParams(0,-2,1));}list.addView(row);}new android.app.AlertDialog.Builder(a).setTitle("Saber · 九种表情").setView(list).setPositiveButton("关闭",null).show();}
 public static void floating(MainActivity a,FrameLayout frame){if(a.prefs.getBoolean("petHidden",false))return;ImageView v=picture(a,0,true);int size=a.dp(60);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(size,size,Gravity.TOP|Gravity.LEFT);lp.leftMargin=Math.max(0,a.getResources().getDisplayMetrics().widthPixels-size-a.dp(22));lp.topMargin=a.dp(a.prefs.getInt("petY",210));frame.addView(v,lp);v.setElevation(a.dp(8));v.setOnClickListener(w->a.startActivity(new Intent(a,PetChatActivity.class)));v.setOnTouchListener(new View.OnTouchListener(){float x,y,ox,oy;boolean moved;public boolean onTouch(View view,android.view.MotionEvent e){if(e.getAction()==0){x=e.getRawX();y=e.getRawY();ox=v.getX();oy=v.getY();moved=false;return true;}if(e.getAction()==2){float dx=e.getRawX()-x,dy=e.getRawY()-y;if(Math.abs(dx)+Math.abs(dy)>a.dp(8))moved=true;if(moved){v.setX(Math.max(0,Math.min(frame.getWidth()-size,ox+dx)));v.setY(Math.max(a.dp(65),Math.min(frame.getHeight()-size-a.dp(68),oy+dy)));}return true;}if(e.getAction()==1){if(!moved)v.performClick();else{v.animate().x(v.getX()<frame.getWidth()/2?0:frame.getWidth()-size).setDuration(160).start();a.prefs.edit().putInt("petY",Math.round(v.getY()/a.getResources().getDisplayMetrics().density)).apply();}return true;}return true;}});}
}
