package com.example.suiri;
import android.app.*;
import android.app.job.*;
import android.content.*;
import android.net.*;
import org.json.*;
import java.net.*;
import java.io.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.zip.GZIPInputStream;

public final class Weather {
 static boolean running;
 static final String[] KINDS={"current","daily","alert"};
 public static boolean enabled(Context c){return TaskStore.prefs(c).getBoolean("weatherEnabled",true)&&Secrets.has(c,"weather")&&!TaskStore.prefs(c).getString("weatherHost","").isEmpty();}
 public static JSONObject data(Context c,String kind){try{return new JSONObject(TaskStore.prefs(c).getString("weather."+kind,"{}"));}catch(Exception e){return new JSONObject();}}
 public static String city(Context c){return TaskStore.prefs(c).getString("weatherCity","上海市区");}
 public static long age(Context c,String kind){long t=TaskStore.prefs(c).getLong("weather.time."+kind,0);return t==0?Long.MAX_VALUE:System.currentTimeMillis()-t;}
 public static boolean dual(Context c){android.content.SharedPreferences p=TaskStore.prefs(c);return p.getBoolean("weatherLocation",true)&&p.getBoolean("weatherLocated",false)&&!WeatherLocation.shanghai(p.getString("weatherRegion",""));}
 public static String summary(Context c){if(!enabled(c))return "Saber · 天气未配置";JSONObject d=data(c,"current");String label=city(c);android.content.SharedPreferences p=TaskStore.prefs(c);if(p.getBoolean("weatherLocated",false)&&System.currentTimeMillis()-p.getLong("weatherLocationTime",0)>WeatherRules.HOUR)label+="（上次位置）";String text=label+" · "+WeatherRules.condition(d)+" "+WeatherRules.temperature(d)+(age(c,"current")>4*WeatherRules.HOUR?" · 待更新":"");if(dual(c)){JSONObject sh=data(c,"shanghai.current");text+="\n上海 · "+WeatherRules.condition(sh)+" "+WeatherRules.temperature(sh)+(age(c,"shanghai.current")>4*WeatherRules.HOUR?" · 待更新":"");}return text;}
 public static String advice(Context c){if(!enabled(c))return "亲爱的master，在设置中连接和风天气，我就能替您留意天气。";if(age(c,"current")>4*WeatherRules.HOUR&&age(c,"daily")>12*WeatherRules.HOUR)return "亲爱的master，天气数据还未更新，请联网后再查看。";String main=WeatherRules.advice(age(c,"current")<=4*WeatherRules.HOUR?data(c,"current"):new JSONObject(),age(c,"daily")<=12*WeatherRules.HOUR?data(c,"daily"):new JSONObject(),age(c,"alert")<=4*WeatherRules.HOUR&&WeatherRules.active(data(c,"alert"),Instant.now()).length()>0,LocalDate.now(Schedule.ZONE));if(dual(c)){String risk=WeatherRules.risks(age(c,"shanghai.current")<=4*WeatherRules.HOUR?data(c,"shanghai.current"):new JSONObject(),age(c,"shanghai.daily")<=12*WeatherRules.HOUR?data(c,"shanghai.daily"):new JSONObject(),age(c,"shanghai.alert")<=4*WeatherRules.HOUR&&WeatherRules.active(data(c,"shanghai.alert"),Instant.now()).length()>0,LocalDate.now(Schedule.ZONE));if(!risk.isEmpty())main+="\n上海："+risk;}return main;}

 public static String stamp(Context c){long time=TaskStore.prefs(c).getLong("weather.time.current",0);return "和风天气 · "+(time==0?"尚未获取":Instant.ofEpochMilli(time).atZone(Schedule.ZONE).format(DateTimeFormatter.ofPattern("MM-dd HH:mm"))+" 获取");}
 static long gap(Context c,String kind){return (kind.equals("daily")?6:dual(c)?2:1)*WeatherRules.HOUR;}
 static boolean due(Context c){android.content.SharedPreferences p=TaskStore.prefs(c);long now=System.currentTimeMillis();if(p.getBoolean("weatherGeoNeeded",false)&&WeatherRules.due(p.getLong("weatherGeoAttempt",0),now,WeatherRules.HOUR))return true;for(String prefix:dual(c)?new String[]{"","shanghai."}:new String[]{""})for(String k:KINDS)if(WeatherRules.due(p.getLong("weather.attempt."+prefix+k,0),now,gap(c,k)))return true;return false;}
 public static void ensure(Context c){JobScheduler jobs=c.getSystemService(JobScheduler.class);if(!enabled(c)){jobs.cancel(4301);jobs.cancel(4302);return;}if(jobs.getPendingJob(4301)==null)jobs.schedule(new JobInfo.Builder(4301,new ComponentName(c,WeatherJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setPersisted(true).setPeriodic(WeatherRules.HOUR).build());if(due(c)&&jobs.getPendingJob(4302)==null)jobs.schedule(new JobInfo.Builder(4302,new ComponentName(c,WeatherJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setMinimumLatency(1000).build());}
 static synchronized void reserve(Context c)throws Exception{android.content.SharedPreferences p=TaskStore.prefs(c);String month=YearMonth.now(Schedule.ZONE).toString();String old=p.getString("weatherMonth","");int used=p.getInt("weatherCount",0);if(!WeatherRules.budget(old,used,month))throw new IOException("本月天气请求已达3000次，暂停刷新");if(!p.edit().putString("weatherMonth",month).putInt("weatherCount",old.equals(month)?used+1:1).commit())throw new IOException("无法保存天气请求计数，已停止请求");}
 static JSONObject request(Context c,String host,String path,String secret)throws Exception{reserve(c);HttpURLConnection h=(HttpURLConnection)new URL("https://"+host+path).openConnection();h.setConnectTimeout(12000);h.setReadTimeout(18000);h.setInstanceFollowRedirects(false);h.setRequestProperty("X-QW-Api-Key",secret);h.setRequestProperty("Accept-Encoding","gzip");try{int code=h.getResponseCode();if(code!=200)throw new IOException(code==401?"和风凭据无效，请核对API Key和Host":code==402?"和风额度不足，已停止本次请求":code==403?"和风权限不足":code==429?"和风请求过于频繁":"天气服务返回 HTTP "+code);try(InputStream raw=h.getInputStream();InputStream in="gzip".equalsIgnoreCase(h.getContentEncoding())?new GZIPInputStream(raw):raw;ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] buf=new byte[4096];int n;while((n=in.read(buf))!=-1){if(b.size()+n>512000)throw new IOException("天气数据过大");b.write(buf,0,n);}return new JSONObject(b.toString("UTF-8"));}}finally{h.disconnect();}}
 public static void sync(Context c){synchronized(Weather.class){if(running)return;running=true;}try{if(!enabled(c))return;ConnectivityManager cm=c.getSystemService(ConnectivityManager.class);NetworkCapabilities net=cm.getNetworkCapabilities(cm.getActiveNetwork());if(net==null||!net.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET))return;android.content.SharedPreferences p=TaskStore.prefs(c);String host=WeatherRules.host(p.getString("weatherHost","")),key=Secrets.get(c,"weather"),lat=p.getString("weatherLat","31.23"),lon=p.getString("weatherLon","121.47");long rev=p.getLong("weatherRevision",0);String error="";boolean changed=false;
 if(p.getBoolean("weatherGeoNeeded",false)&&WeatherRules.due(p.getLong("weatherGeoAttempt",0),System.currentTimeMillis(),WeatherRules.HOUR)){p.edit().putLong("weatherGeoAttempt",System.currentTimeMillis()).commit();try{JSONObject geo=request(c,host,"/geo/v2/city/lookup?location="+lon+","+lat+"&lang=zh&number=1",key);JSONObject place=geo.getJSONArray("location").getJSONObject(0);if(rev==p.getLong("weatherRevision",0)){String district=place.optString("name"),city=place.optString("adm2");p.edit().putString("weatherRegion",place.optString("adm1")).putString("weatherCity",city.equals(district)?city:city+" "+district).putBoolean("weatherGeoNeeded",false).commit();changed=true;}}catch(Exception e){error="位置名称暂未获取，天气仍按定位坐标查询";}}
 for(String prefix:dual(c)?new String[]{"","shanghai."}:new String[]{""})for(String kind:KINDS){if(Thread.currentThread().isInterrupted()||!enabled(c)||rev!=p.getLong("weatherRevision",0))break;long now=System.currentTimeMillis();String slot=prefix+kind;if(!WeatherRules.due(p.getLong("weather.attempt."+slot,0),now,gap(c,kind)))continue;p.edit().putLong("weather.attempt."+slot,now).commit();try{String coords=prefix.isEmpty()?lat+"/"+lon:"31.23/121.47";String path=(kind.equals("alert")?"/weatheralert/v1/current/":"/weather/v1/"+kind+"/")+coords+"?lang=zh&localTime=true"+(kind.equals("daily")?"&days=3":"");JSONObject result=request(c,host,path,key);if(kind.equals("current"))result.getJSONObject("temperature").getDouble("value");if(kind.equals("daily"))result.getJSONArray("days");if(kind.equals("alert")&&!result.has("alerts")&&!WeatherRules.obj(result,"metadata").optBoolean("zeroResult"))throw new JSONException("缺少预警状态");if(rev!=p.getLong("weatherRevision",0)||!enabled(c))break;p.edit().putString("weather."+slot,result.toString()).putLong("weather.time."+slot,now).commit();changed=true;}catch(Exception e){error=slot+"："+(e instanceof IOException?e.getMessage():"天气返回数据异常");if(error.contains("额度")||error.contains("3000")||error.contains("凭据"))break;}}
 if(rev==p.getLong("weatherRevision",0))p.edit().putString("weatherError",error).putLong("weatherUpdated",System.currentTimeMillis()).apply();if(changed){notifyWeather(c);SuiRiWidget.refresh(c);}
 }catch(Exception e){TaskStore.prefs(c).edit().putString("weatherError","天气配置或连接失败，请检查Host与凭据").putLong("weatherUpdated",System.currentTimeMillis()).apply();}finally{synchronized(Weather.class){running=false;}}}
 static void notifyWeather(Context c){android.content.SharedPreferences p=TaskStore.prefs(c);if(!p.getBoolean("weatherNotify",true)||!Reminders.notifications(c))return;JSONArray alerts=age(c,"alert")<=4*WeatherRules.HOUR?WeatherRules.active(data(c,"alert"),Instant.now()):new JSONArray();String text=advice(c),tag="";if(alerts.length()>0){JSONObject a=alerts.optJSONObject(0);tag="alert:"+a.optString("id")+a.optString("issuedTime");text+="\n"+a.optString("headline")+"\n"+a.optString("senderName")+" · "+a.optString("issuedTime");}else{if(age(c,"current")>4*WeatherRules.HOUR||(text.contains("休息时间")&&!text.contains("\n上海："))||LocalTime.now(Schedule.ZONE).getHour()<7||LocalTime.now(Schedule.ZONE).getHour()>21)return;tag="daily:"+LocalDate.now(Schedule.ZONE);}if(tag.equals(p.getString("weatherNotified","")))return;NotificationManager n=c.getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel("saber_weather","Saber 天气提醒",NotificationManager.IMPORTANCE_DEFAULT));PendingIntent open=PendingIntent.getActivity(c,4300,new Intent(c,PetChatActivity.class).putExtra("weather",true),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);n.notify("saber-weather",4300,new Notification.Builder(c,"saber_weather").setSmallIcon(android.R.drawable.ic_menu_compass).setLargeIcon(Saber.head(c)).setContentTitle("Saber · 亲爱的master，请留意天气").setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setContentIntent(open).setAutoCancel(true).build());p.edit().putString("weatherNotified",tag).apply();}
}
